spring.application.name=customer-service

spring.jpa.hibernate.ddl-auto=update

spring.datasource.username=${MYSQLUSER:backend1}
spring.datasource.password=${MYSQLPASSWORD:12345}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.url=jdbc:${MYSQL_URL:mysql://localhost:3306/customers}
server.port=${MYSQLPORT:8081}